# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24e5ffabd97827bcc3965adf9b6d83c1b8df766deeedd8e05a37d07a5a0fef38cd493222b72210638541d026a0c956e24adf2afc4015387b0ff55d1de3a10bbe

test:
  secret_key_base: 79f6df457da686910acc881d7c01b497b088cb255767d9e2f2d0114e90c1857b8b017ff26573c654b0ad7d585269721fe2b1bae256c699652f34b8c741ac6b5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
